language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - master

install:
- wget https://github.com/golang/dep/releases/download/v0.3.0/dep-linux-amd64.zip
- unzip dep-linux-amd64.zip
- chmod +x dep
- ./dep ensure
- go get -u github.com/alecthomas/gometalinter
- gometalinter -u -i -f

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic
- gometalinter --vendor --config=./gometalinter.json ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
